### PR TITLE
feat: update to use node20

### PR DESCRIPTION
**Pull request by chenrui333**
This is consistent with all the recent github action updates. (mostly in actions repos, like actions/checkout, actions/setup-node, etc.)

-------

Node12 was deleted from runner. Node20 was added to Actions Runner on v2.308.0.
Node16 has en end of life on 11 Sep 2023.

This PR updates the default runtime to node20, rather then node16

relates to https://github.com/actions/runner/pull/2732

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @goto-bus-stop

**Comment by chenrui333** [comment]
looks like there is some issue with testing against zig 0.11.0, https://github.com/chenrui333/setup-zig/actions/runs/7296724152/job/19884920370

**Comment by goto-bus-stop** [comment]
thanks for the PR! zig 0.11 changed the build system so i've pulled that out into https://github.com/goto-bus-stop/setup-zig/pull/62.

**Comment by chenrui333** [comment]
@goto-bus-stop also the setup action should be bumped to v3 per this upgrade. :)

**Comment by goto-bus-stop** [comment]
imo it's OK to treat this bump as non-breaking since the environment it runs in is known to be compatible (aside from self-hosted runners, maybe?) and the cost of a major version bump on actions is very high as most projects do not have dependabot configured for actions.

**Pull request merged**
